### ISSUE TITLE
Error while exporting some maps

### ISSUE THREAD

**Issue by DearFox** [kilometerbob/Minecraft-Map-Exporter#1]
When exporting some maps, I get an error:
Traceback (most recent call last):
  File "...\main.py", line 58, in <module>
    log = log + num + '\n'
TypeError: can only concatenate str (not "int") to str
[map_26006.zip](https://github.com/kilometerbob/Minecraft-Map-Exporter/files/7850611/map_26006.zip)
![image](https://user-images.githubusercontent.com/59219907/149041078-0ead5704-bc80-4bbd-9545-e3f983ee0c49.png)
It seems that the reason for this is the unloaded territory (possibly)

**Comment by DearFox** [comment]
I was able to fix this by simply commenting out line 58

**Comment by roberthoffman04** [comment]
ah yes sorry that was mostly a debugging line for me and should have been removed from the final version. All it does is create a log.txt which saves the block ID of any block that is outside of the color pallette
