### ISSUE TITLE
The color picker does not match the minecraft color picker.

### ISSUE THREAD

**Issue by DearFox** [kilometerbob/Minecraft-Map-Exporter#2]
I was converting maps from the server and noticed that the colors do not correspond to the real ones (some shades are just a little different, but what is much worse is that some colors are generally wrong)
It should be:
![image](https://user-images.githubusercontent.com/59219907/149136158-ddf055c2-36d5-4ad2-a7da-3eeefa37dc50.png)
How does this come about using your palette:
![map_10385](https://user-images.githubusercontent.com/59219907/149136179-d7025396-6866-4ce7-b8d3-4342c23ead41.png)

I like your program, it allowed me to see over 500 maps from the server I played on, but I would like to get more correct colors on the maps.

The maps that I use for conversion are made on versions ~ 1.14-1.16

**Comment by DearFox** [comment]
I tried to make my own palette of colors, but did not understand why you have 4 colors instead of 3 standard ones.
I was trying to take the color picker from https://rebane2001.com/mapartcraft and convert it to color.txt (I duplicated the last color for each tone color to get 4 colors in place of 3 and also added four lines of colors to the beginning) and I even succeeded, but this is still not completely correct.

**Comment by DearFox** [comment]
I decided to reconfigure my color.txt file and used a screenshot from the game as a basis.
I think I made it as believable as possible
![image](https://user-images.githubusercontent.com/59219907/149159509-d800466d-f356-40ec-a05c-f44dc95261cc.png)
Yes! I was able to reconfigure it to work correctly with maps 1.16.x
![image](https://user-images.githubusercontent.com/59219907/149159913-10bfbe83-28e5-4a6d-849e-bdb540876256.png)

**Comment by roberthoffman04** [comment]
Sorry you ended up having issues. I based the color pallet of of [this list](https://minecraft.fandom.com/wiki/Map_item_format#Color_table) from the Minecraft wiki to generate the palette. Do you mind telling me what blocks were giving you issues. I don't need to know exactly where they were

**Comment by roberthoffman04** [comment]
It would also be great to have the map file itself if that's possible

**Comment by DearFox** [comment]
Yes, sure
Here is the map file with colors on which I tested it and my color file for your script.
[Minecraft-Map-Exporter-main.zip](https://github.com/kilometerbob/Minecraft-Map-Exporter/files/7863031/Minecraft-Map-Exporter-main.zip)

**Comment by roberthoffman04** [comment]
Thanks! After some preliminary investigation it seems the order for the color values in the color.txt are out of place for a few sets of them. Usually its just a matter of swapping them but its hard to know what's wrong without large data sets to test

**Comment by roberthoffman04** [comment]
I just want to say thank you as you actually exposed a big issue with my color pallete I was actually missing the color codes for green terracotta and it was making every value appear one to the left. Its now corrected and the updated color.txt should be posted. Please don't hesitate from posting any further issues.
