### ISSUE TITLE
Request to speed up the script

### ISSUE THREAD

**Issue by DearFox** [kilometerbob/Minecraft-Map-Exporter#3]
I have more than 50k map files, the script does not allow you to select the entire folder, but only a few files, if I knock out everything, the selection window will simply freeze.
Also, the conversion rate is very slow. It took about 5-10 minutes to make 4k maps.

**Comment by roberthoffman04** [comment]
I'll see what I can do but the nature of the conversion itself just takes a while. If its not to much trouble could you provide a sample size of 150-250 maps so I can better test program functionality

**Comment by DearFox** [comment]
[data_full.zip](https://github.com/kilometerbob/Minecraft-Map-Exporter/files/8710265/data_full.zip)

**Comment by roberthoffman04** [comment]
Thank you. It may take a while to make improvements but a large data set should help development go faster

**Comment by roberthoffman04** [comment]
I am not quite finished yet but I have managed to cut the time in almost half and felt like I should deliver you a quick fix. The source code now contains the new changes however I'm having some trouble compiling it to the EXE. Issue will hopefully be fixed tomorrow but I am too tired tonight

EDIT: EXE file is now compiled and released hover it is buggy and if possible I still recommend the raw source code

**Comment by DearFox** [comment]
I am using py version
besides, for my needs, I changed it a little in order to save not only pictures but also the coordinates on which the map was created

**Comment by roberthoffman04** [comment]
Ah ok you may have to rework your additions a bit however that still should be perfectly possible. The main thing that needs to be changed for the performance increase is have the color list preloaded into the file like it is in the new version. most other differences had minimal performance impact

**Comment by roberthoffman04** [comment]
I believe the code is now running as fast as it currently can, or at least as fast as my expertise will allow. Make sure you have merging turned off if you are going for performance. As for extremely large amounts of files breaking the program there is not much I can do about that as it seems to an issue with the libraries I use and not my own code.

I'm considering this closed but will leave this open as it is still an ongoing issue

**Comment by roberthoffman04** [comment]
I have another massive speed improvement. I multithreaded the code so It'll run on every core of the CPU. for me it was about a 300% increase but if you have more cores it should go faster. Obviously at some point it becomes an issue of writing the files fast enough.

![image](https://user-images.githubusercontent.com/58479577/194453715-54235d35-56bb-46c2-82eb-8fbfea1d3c17.png)
Here is the raw speed(In seconds) for running just under a thousand maps.

I'm officially calling this closed now.
